version: '3.5'
services:
  frontend:
    container_name: personal_site_frontend
    image: ebiven/vue-cli
    command:
      - /bin/sh
      - '-c'
      - |
        yarn install
        yarn run build
        yarn run start --hostname 0.0.0.0 -p 3500
    working_dir: /frontend
    ports:
      - 3500:3500
    env_file: .env
    volumes:
      - ./frontend:/frontend:cached
    environment:
      - NODE_ENV=production
    networks:
      - default

volumes:
  db-data: null
  bundle-cache: null

networks:
  default:
    external: true
    name: global